[build]
target = "riscv64gc-unknown-none-elf"

# 使用我们的 kernel script 来进行链接
[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/linker/qemu.ld",
]


runner = """
    qemu-system-riscv64 \
    -machine virt -bios none \
    -m 3G -smp 3 -nographic \
    -drive file=../fs.img,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
    -netdev user,id=net0,hostfwd=udp::26999-:2000 -object filter-dump,id=net0,netdev=net0,file=packets.pcap \
    -device e1000,netdev=net0,bus=pcie.0 \
    -kernel
    """

[term]
verbose = true