[package]
name = "kernel"
version = "0.1.0"
authors = ["KuangjuX <qcx@tju.edu.cn>", "Jaic1 <506933131@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.3"
bitflags = "2.13.1"
array-macro = "2.1.8"
allocator = { path = "../allocator" }

[features]
default = []
sbi = []
debug = []
kernel_debug = []
kernel_warning = []
verbose_init_info = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
