#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"include/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");

entry("sem_get");
entry("sem_put");
entry("sem_down");
entry("sem_up");
entry("sem_init");

entry("mkfifo");
entry("fifo_get");
entry("fifo_write");
entry("fifo_read");
entry("fifo_put");

entry("clone");
entry("join");

entry("msg_alloc");
entry("msg_get");
entry("msg_send");
entry("msg_recv");